### ISSUE TITLE
Issue installing in macOS Mojave w/ command line tools for Xcode 10

### ISSUE THREAD

**Issue by maxienbelgica** [vtraag/leidenalg#1]
Apple deprecated deprecated libstdc++ a few years ago, but finally eliminated it from the latest release of the command line tools. This means that the installation of leidenalg throws an error while compiling (i.e., libstdc++ not found, please use libc++). Changing the compiler manages to install the package but introduces more errors later. 

The easiest solution I found was to delete Xcode 10 and install Xcode 9.4 w/ the command line tools. Everything works just fine. Technically, deleting Xcode 10 is not necessary but I haven't tried this. Moreover, installing just the command line tools (without Xcode) should work as well if you have no other need for Xcode.

**Comment by vtraag** [comment]
Thanks for the report! I'll look into whether I can link to libc++ if it is compiled with the latest Xcode to avoid this issue.

**Comment by gokceneraslan** [comment]
Alternatively, it works with Brew installation of g++ e.g. `export CXX=g++-8; pip install leidenalg`

**Comment by vtraag** [comment]
@maxienbelgica Could you perhaps provide the full output when you get the error that it should use libc++? I found a potential solution (https://github.com/rflamary/POT/pull/72/files), but I need to know in which circumstance this exactly pops up.

**Comment by Giovanni1085** [comment]
Hello @vtraag, I am experiencing the same issue, here the error:

```
gcc -bundle -undefined dynamic_lookup -L/anaconda3/envs/hes/lib -arch x86_64 -L/anaconda3/envs/hes/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/edgeobject.o build/temp.macosx-10.7-x86_64-3.7/src/common.o build/temp.macosx-10.7-x86_64-3.7/src/py2compat.o build/temp.macosx-10.7-x86_64-3.7/src/graphobject.o build/temp.macosx-10.7-x86_64-3.7/src/indexing.o build/temp.macosx-10.7-x86_64-3.7/src/igraphmodule.o build/temp.macosx-10.7-x86_64-3.7/src/bfsiter.o build/temp.macosx-10.7-x86_64-3.7/src/convert.o build/temp.macosx-10.7-x86_64-3.7/src/vertexobject.o build/temp.macosx-10.7-x86_64-3.7/src/random.o build/temp.macosx-10.7-x86_64-3.7/src/edgeseqobject.o build/temp.macosx-10.7-x86_64-3.7/src/error.o build/temp.macosx-10.7-x86_64-3.7/src/vertexseqobject.o build/temp.macosx-10.7-x86_64-3.7/src/arpackobject.o build/temp.macosx-10.7-x86_64-3.7/src/attributes.o build/temp.macosx-10.7-x86_64-3.7/src/filehandle.o build/temp.macosx-10.7-x86_64-3.7/src/pyhelpers.o igraphcore/lib/libigraph.a -Ligraphcore/lib -L/usr/local/lib -L/usr/lib -lxml2 -lz -lm -lstdc++ -o build/lib.macosx-10.7-x86_64-3.7/igraph/_igraph.cpython-37m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/envs/hes/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-pwx5ir39/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-l12wls8d/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-pwx5ir39/python-igraph/
```

For reference:

```
> brew info gcc
gcc: stable 8.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/8.2.0 (1,413 files, 295.5MB) *
  Poured from bottle on 2018-11-29 at 14:36:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
```

```
> gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

@gokceneraslan's solution did not work for me.

**Comment by maxienbelgica** [comment]
I'm sorry I haven't had the chance to reinstall Xcode 10 to replicate the error yet, but Giovanni's error seems to be what I was experiencing. I also tried forcing g++ 8, that installed the package correctly but brought compatibility errors when running.

**Comment by Giovanni1085** [comment]
> @Giovanni1085 could you test the code in the pull-request #3 ? You should be able to install using `pip install -e .` inside the source directory. Unfortunately, the Mac OS test setup in [Travis](https://travis-ci.org/vtraag/leidenalg/jobs/461655830#L58) does not work properly, so I cannot test it.

Finally managed to try this out: pull-request #3 works well! I had to do these steps beforehand (Mojave 10.14.2, Python 3.7.0):
* `xcode-select --install`
* `brew update`
* `brew upgrade`
* `export MACOSX_DEPLOYMENT_TARGET=10.14`
* then `pip install -e .`

All tests succeed afterwards.

**Comment by vtraag** [comment]
Thanks for testing!

The Mac OS version is now also available from [`conda-forge`](https://anaconda.org/conda-forge/leidenalg). This does not address the problem for compilation with XCode 10, so I'll leave the issue open. But at least it provides a work around, as you are no longer required to compile it yourself.

**Comment by vtraag** [comment]
Binary wheels are now being build for the new release for all platforms, including binaries for macOS. This should fix this issue.
