### ISSUE TITLE
legacy-install-failure python 3.10

### ISSUE THREAD

**Issue by joyduck** [vtraag/leidenalg#103]
try to install leidenalg  with python 3.10.4 using 
pip install leidenalg
get a error: legacy-install-failure

could you please suggest a resolution? Thanks

**Comment by vtraag** [comment]
It's not directly clear to me what the problem is. I just released a new version 0.8.10, perhaps you could try to install it now? If you still encounter problems, please include also the detailed output from the installation, that should be helpful for debugging the problem.

**Comment by joyduck** [comment]
installed successfully, problem resolved. Thanks so much.
