### ISSUE TITLE
Installation on Apple M1

### ISSUE THREAD

**Issue by fsvbach** [vtraag/leidenalg#110]
Hi, 

I've been using leidenalg on my older Apple without any problems. Now that our faculty upgraded the machines to Apple M1 chips, I can't install the package with `pip install leidenalg.` I get the error message:

```
igraph uses CMake as the build system. You need to install CMake before compiling igraph.
      Build failed for the C core of igraph.
```

I've also seen the closed issue #88 and tried to install the newer version directly from GitHub - which gave me the same error. Am I missing something?

Thanks a lot for any help!

Edit: I've already installed CMake on the machine from [https://cmake.org/download/](https://cmake.org/download/) and also installed igraph via `pip install igraph` which worked perfectly.

**Comment by vtraag** [comment]
Hmm, I'm not sure what has happened, it seems that 0.8.10 on PyPI doesn't include the macos ARM64 builds. I'll have to check it out.

As an alternative, you could perhaps try to install in `conda` from the `conda-forge` channel?

I am updating the package today to support the recent `igraph` 0.10.x release, hopefully this will also solve your problem, and I'll be able to upload a proper ARM64 build as well.

**Comment by vtraag** [comment]
The new release 0.9.0 now also includes ARM64 builds from PyPI. I'll close the issue for now, assuming this fixes your problem. If not, let me know, and we can re-open the issue!

**Comment by fsvbach** [comment]
Thanks, it works now!
