### ISSUE TITLE
release compatible with igraph >= 0.10?

### ISSUE THREAD

**Issue by jboynyc** [vtraag/leidenalg#112]
Currently the `igraph` dependency is [pinned](https://github.com/vtraag/leidenalg/blob/91fbe8ced00f7e0905578583d8b748388dc84b1b/setup.py#L838) to a version < 0.10. This means packages depending on `leidenalg` cannot use the latest `igraph` releases. 

Any chance of a new release of this package? And, in case there are blockers, are there any I could help with?

**Comment by vtraag** [comment]
Version 0.9.0 was just pushed to PyPI, the version will soon enough also propagate to Anaconda. I'll close the issue for now. If you run into any issues with the new release, let me know!
