### ISSUE TITLE
Can't use `find_partition` function

### ISSUE THREAD

**Issue by jsliacan** [vtraag/leidenalg#12]
I use Fedora 30, python & gcc versions below. Install went alright, although I used the `--user` option to avoid installing as a root. It shouldn't matter though. 

When I use `find_partition` function, sometimes it works and sometimes it doesn't. See below (first time it worked, second time with identical input, it didn't). 

I could investigate the error further, but maybe you have an idea right away. Am I doing something wrong or is it a legitimate issue? How can I circumvent it? Thanks!

```
$ python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import leidenalg
>>> import igraph as ig
>>> G = ig.Graph.Erdos_Renyi(100,0.1)
>>> part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition)
>>> part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition)
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

**Comment by vtraag** [comment]
Thanks for the report!

Sounds like it is a memory issue, or possibly something related to the random number generator. I'll have to look into it before I can say more about it. Perhaps you can compile with `--debug` so that  the error is a bit more revealing?

What version of `leidenalg` are you using? Did you compile yourself from the master branch, or did you use the source code from the 0.7.0 release? Similarly, what version of `igraph` did you use, and how did you install/compile it?

**Comment by jsliacan** [comment]
So quick, thanks!

I installed with `pip3 install python-igraph --user` and `pip3 install leidenalg --user`. Versions are `python-igraph-0.7.1.post6` and `leidenalg-0.7.0`, respectively. Not sure how to use `--debug` option. From source, python-igraph installation didn't work with some `gcc` failing somewhere -- I'd have to re-run it to find out more. 

I'm happy to find out more if you tell me how. Thanks again

**Comment by vtraag** [comment]
In `pip` you should be able to use
```
pip3 install --global-option build --global-option --debug ...
```

**Comment by jsliacan** [comment]
Thanks, that worked for install. So first I uninstalled both `leidenalg` and `python-igraph` and then installed them as you suggest. Unfortunatelly, no change in the error message. 

```
$ python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph as ig
>>> import leidenalg
>>> G = ig.Graph.Erdos_Renyi(100,0.1);
>>> part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition);
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

**Comment by vtraag** [comment]
Thanks again for the bug report! I've managed to track the problem down. For some reason it didn't appear under another OS, but it did under Fedora. I believe that #13 fixes the issue. Could you confirm whether that solves your issue? You can checkout the pull request, and install using
```
pip3 install -e .
```
when you are in the directory where the code from the PR resides.

**Comment by jsliacan** [comment]
That's neat. I did a loop of 200x to see if it fails, but it works nicely. Also my other code that needs it works OK now. Seems to be fixed. Thanks!

**Comment by vtraag** [comment]
Great!

It's actually nice that you caught the bug, otherwise it might have gone unnoticed for much longer, so thank you!
