### ISSUE TITLE
hello，How to take out the vertex after community-discovery？

### ISSUE THREAD

**Issue by swx-10** [vtraag/leidenalg#121]
After I do community discovery, how can I take out these vertices in each community？

```
partition = la.find_partition(G, la.ModularityVertexPartition)
```
Looking forward to your response！

**Comment by vtraag** [comment]
Thanks @ragibson!

If anyone is curious to understand how to use `VertexClustering`, you can refer to the documentation of igraph. In particular, the `Clustering` (from which `VertexClustering` derives) describes the usage quite clearly: https://igraph.org/python/api/latest/igraph.clustering.Clustering.html.
