### ISSUE TITLE
leidenalg.CPMVertexPartition reference for negative weights

### ISSUE THREAD

**Issue by alisonpeard** [vtraag/leidenalg#123]
Hi,

Thanks for this great package!

The documentation states that the CPMVertexPartition is "well-defined for both positive and negative edge weights", but there is no mention of negative weights in the referenced paper: 

Traag, V. A., Van Dooren, P., & Nesterov, Y. (2011). Narrow scope for resolution-limit-free community detection. Physical Review E, 84(1), 016114. [10.1103/PhysRevE.84.016114](http://doi.org/10.1103/PhysRevE.84.016114)

Is there a paper related to this algorithm that proves this statement?

**Comment by ragibson** [comment]
That reference does appear to discuss negative links, both in reference to a [cited paper on a Potts model](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.81.046114) and [the author's own extension of a Potts model to negative links](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.80.036115).

In any case, this seems clear by inspection.
> [CPMVertexPartition](https://leidenalg.readthedocs.io/en/stable/reference.html#cpmvertexpartition) [...] This quality function is well-defined for both positive and negative edge weights.

The Constant Potts Model's quality function basically just adds the weights of the network and subtracts a constant, so there shouldn't be any issues with negative weights.

**Comment by vtraag** [comment]
Thanks @ragibson for answering @alisonpeard's question!

In addition to what @ragibson already said, you can find some more details in [my thesis](http://hdl.handle.net/2078.1/134615), in particular section 5.2.
