### ISSUE TITLE
How should I assign weights to different layers when doing community detection?

### ISSUE THREAD

**Issue by chansigit** [vtraag/leidenalg#128]
Dear author,
I am performing community detection on a multiplex network (same sets of nodes, different layers, no inter-layer edges)

I hope to assign different weights to different layers so that some node types of edges could be more important in the community formation.

How can I achieve this in "find_partition_multiplex"? I failed to find the answer from the doc.

Looking forward to your answer.

Thanks!

**Comment by geniusadventurer** [comment]
Hello, I am doing the same thing as you do. You can read https://leidenalg.readthedocs.io/en/latest/multiplex.html#layer-multiplex for details. You can use the function la.CPMVertexPartition to generate the network, and then use the function optimiser.optimise_partition_multiplex. You can assign different weights to different layers in the parameter 'layer_weights' in the latter function.

**Comment by vtraag** [comment]
@geniusadventurer, thanks for replying to the question of @chansigit ! PR #129 by @bfarahdel seems to have made this a little bit easier.
