### ISSUE TITLE
which function implements multiple time slices [9]?

### ISSUE THREAD

**Issue by rabbit200** [vtraag/leidenalg#130]
Hi, I'm not sure if your find_partition_temporal function implements the algorithm [9], am I right?

**Comment by vtraag** [comment]
You can find documentation about the temporal community detection here: https://leidenalg.readthedocs.io/en/stable/multiplex.html#temporal-community-detection

This is based on:

Mucha, P. J., Richardson, T., Macon, K., Porter, M. A., & Onnela, J.-P. (2010). Community structure in time-dependent, multiscale, and multiplex networks. *Science*, 328(5980), 876–8. [10.1126/science.1184819](http://doi.org/10.1126/science.1184819)

**Comment by rabbit200** [comment]
> You can find documentation about the temporal community detection here: https://leidenalg.readthedocs.io/en/stable/multiplex.html#temporal-community-detection
> 
> This is based on:
> 
> Mucha, P. J., Richardson, T., Macon, K., Porter, M. A., & Onnela, J.-P. (2010). Community structure in time-dependent, multiscale, and multiplex networks. _Science_, 328(5980), 876–8. [10.1126/science.1184819](http://doi.org/10.1126/science.1184819)

Thanks a lot!
