### ISSUE TITLE
On the implementation of leidenalg

### ISSUE THREAD

**Issue by xia867726328** [vtraag/leidenalg#139]
When I was debugging the environment, I found that you did not upload the _c_ leiden file, and I encountered problems when trying to implement it by myself. Could you please send this file to me?No matter whether you agree or not, best wishes to you. I would appreciate it if you could help me.
Thanks and regards!

**Comment by vtraag** [comment]
I'm not entirely sure I understand your request. The entire C++ code is available from https://github.com/vtraag/libleidenalg.
