### ISSUE TITLE
AttributeError: module 'igraph' has no attribute 'VertexClustering' with latest igraph

### ISSUE THREAD

**Issue by Zethson** [vtraag/leidenalg#144]
`import leidenalg` results in

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeth/miniconda3/envs/pertpy/lib/python3.10/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/home/zeth/miniconda3/envs/pertpy/lib/python3.10/site-packages/leidenalg/functions.py", line 18, in <module>
    from .VertexPartition import *
  File "/home/zeth/miniconda3/envs/pertpy/lib/python3.10/site-packages/leidenalg/VertexPartition.py", line 5, in <module>
    class MutableVertexPartition(_ig.VertexClustering):
AttributeError: module 'igraph' has no attribute 'VertexClustering'
```

Versions:
```
python = 3.10.6
igraph = "^0.10.6"
python-igraph = "^0.10.6"
leidenalg = "^0.10.0"
```

**Comment by Zethson** [comment]
I played around with igraph and the issue does not appear with igraph version 0.10.4 or smaller. They made two patch releases (0.10.5 - not tested; and 0.10.6 which does not work)

**Comment by vtraag** [comment]
Sorry, I can't reproduce this, starting fro a clean `conda` environment:

```
conda create -n test leidenalg -c conda-forge
```

which in this case installs `leidenalg=0.10.0` and `python-igraph=0.10.6`. Could you please show how you installed all packages?

**Comment by Zethson** [comment]
Huh, now I can't reproduce it either. IDK what happened earlier :/

I'll get back to you when I'll run into it again

**Comment by vtraag** [comment]
OK, no problem!

As a further note, I also can't reproduce this in a clean `venv` installing `leidenalg` and `igraph` using `pip`.

**Comment by szhorvat** [comment]
> python = 3.10.6
> igraph = "^0.10.6"
> python-igraph = "^0.10.6"
> leidenalg = "^0.10.0"

Just a heads up: [`python-igraph` is just a redirect to `igraph`](https://pypi.org/project/python-igraph/), and it will soon cease to be updated. Please only `pip install` the `igraph` package, not `python-igraph`.

**Comment by vtraag** [comment]
> Just a heads up: [`python-igraph` is just a redirect to `igraph`](https://pypi.org/project/python-igraph/), and it will soon cease to be updated. Please only `pip install` the `igraph` package, not `python-igraph`.

Yes, this holds for `pip` indeed. However, note that the OP is using `conda`. In `conda`, [`igraph`](https://github.com/conda-forge/igraph-feedstock) refers to the C core, while [`python-igraph`](https://github.com/conda-forge/python-igraph-feedstock) refers to the Python interface. See https://github.com/conda-forge/python-igraph-feedstock/issues/42 for a discussion about this in the context of the `python-igraph` → `igraph` transition on PyPI. Note that they also host [`r-igraph`](https://github.com/conda-forge/r-igraph-feedstock), so from that point of view the naming makes sense.
