### ISSUE TITLE
How to cite leidenalg?

### ISSUE THREAD

**Issue by RenGroup** [vtraag/leidenalg#147]
Thanks for your efforts on such a nice package. I recently used this package in my network analysis, and I want to cite the package appropriately. Although there are 10 references on the web page, I'm still not sure which reference(s) I should cite. Could you help me with this? Thanks in advance.

**Comment by RenGroup** [comment]
Oh, I found one from the paper: 
"Traag, V. A. leidenalg 0.7.0. Zenodo, https://doi.org/10.5281/zenodo.1469357 https://github.com/vtraag/leidenalg. Source Code (2018)"

**Comment by vtraag** [comment]
You can cite the paper https://doi.org/10.1038/s41598-019-41695-z, or you can cite the software directly https://zenodo.org/records/8147844 (you can then also specify which specific version you used).

**Comment by vtraag** [comment]
And thanks, good to hear it's useful to you!
