### ISSUE TITLE
conda installation fails: ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21'  not found

### ISSUE THREAD

**Issue by fidelram** [vtraag/leidenalg#2]
After installing leidenalg with conda I got the following error:

```bash
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21'  not found
```
I could solve it by downgrading to  `libgcc==5.2.0` (my original version was 7.2.0)

Initially, I tried to install with `pip` but got the error: ` Could not download and compile the C core of igraph.`. Probably, I could have solve this issue by setting the source of igraph but I tried conda instead.

Maybe this is helpful if anyone has the same problem.

**Comment by vtraag** [comment]
Thanks for reporting the issue! Could I ask what OS your are on?

**Comment by fidelram** [comment]
Scientific Linux. However, most software comes from my own Anaconda installation.

**Comment by vtraag** [comment]
I can't seem to reproduce the problem. When I setup a Docker of Scientific Linux (7) from https://hub.docker.com/r/scientificlinux/sl/, install miniconda 3 and do

```
conda install -c conda-forge igraph python-igraph
conda install -c vtraag leidenalg
```
everything works correctly. Could you perhaps report exactly how to reproduce the problem from scratch (i.e. from a clean Scientific Linux docker)?

**Comment by fidelram** [comment]
Something nasty is probably happening on my installation. I hope that at least this issue could help anyone else having the same problem.

Thanks for your time on checking this issue.

**Comment by vtraag** [comment]
Thanks for reporting. Hope it will help some others indeed!

**Comment by kaizen89** [comment]
I also got this error message
```
Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
```
What do you advise?

**Comment by vtraag** [comment]
@kaizen89, I assume you are not trying to install using `conda`? It is probably a separate issue from the one reported here.

The problem is that the C core of `igraph` needs to be installed and compiled separately from the `python-igraph` interface, and the `leidenalg` package which is developed on top of that. If you are on a Unix type system, it should be feasible to compile this. If you are on Windows, this is more difficult, and it is by far the easiest to simply install the package using `conda`.

**Comment by kaizen89** [comment]
I'm on Linux, I tried with Conda and I got this
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                 



Package wheel conflicts for:
leidenalg -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
leidenalg -> python[version='>=3.6,<3.7.0a0'] -> openssl=1.0 -> ca-certificates
Package setuptools conflicts for:
leidenalg -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
python=3.7 -> pip -> setuptools
Package pip conflicts for:
python=3.7 -> pip
leidenalg -> python[version='>=3.6,<3.7.0a0'] -> pip
Package python conflicts for:
python=3.7
Package certifi conflicts for:
leidenalg -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package python-igraph conflicts for:
leidenalg -> python-igraph[version='>=0.7.1.0']
```

**Comment by vtraag** [comment]
OK, thanks for the report. I'll have to look into it.

**Comment by kaizen89** [comment]
I was able to install after I installed the source library from https://igraph.org/c/#downloads.
Thanks

**Comment by vtraag** [comment]
Good to hear! I'll look into the conflict with versions nonetheless...
