### ISSUE TITLE
Empty graph exception handling - segmentation fault

### ISSUE THREAD

**Issue by pgilders** [vtraag/leidenalg#20]
Hi Vincent,

I discovered an issue which I don't fully understand but thought would be worth recording. When an empty graph - no nodes or edges - is supplied to find_partition_temporal (I imagine other functions too), something happens whereby the C library uses excessive memory / addresses invalid memory, throwing a segmentation fault and causing the OS to kill the process (occasionally crashing my IDE depending on how it's run). 

The error message when running within joblib reads: "A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11)}". 

Having discovered the issue, I obviously removed the empty graphs from analysis before running the community detection (which I probably should have been doing anyway...). It would be good in the future for the library to handle these cases before the empty graph reaches the C layer and throws the ugly, python-crashing error. 

Thank you for putting together the package.

Patrick

**Comment by vtraag** [comment]
Thanks for finding this! It turned out to be a bug when shuffling some vector of nodes.
