### ISSUE TITLE
Problem with resolution parameter

### ISSUE THREAD

**Issue by fedeago** [vtraag/leidenalg#21]
Goodmorning and thank you for your work.

I have some problem when I try to set the resolution parameter.

`res = leidenalg.find_partition(g, leidenalg.ModularityVertexPartition, seed=rands, n_iterations= n_iterations, resolution_parameter= parameter)`

`~.../lib/python3.6/site-packages/leidenalg/functions.py in find_partition(graph, partition_type, initial_membership, weights, n_iterations, seed, **kwargs)
     82   partition = partition_type(graph,
     83                              initial_membership=initial_membership,
---> 84                              **kwargs)
     85   optimiser = Optimiser()
     86 

TypeError: __init__() got an unexpected keyword argument 'resolution_parameter'
`

How can I set this parameter?

**Comment by vtraag** [comment]
In case anybody else comes across this: `ModularityVertexPartition` does not accept a `resolution_parameter`, you should use `RBConfigurationVertexPartition` instead.
