### ISSUE TITLE
Accept kNN graph in form of sparse adjacency matrix as an input

### ISSUE THREAD

**Issue by dkobak** [vtraag/leidenalg#25]
Thanks for the wonderful library. I am currently trying to use it to cluster a dataset using its kNN graph. Here is how I am doing it:

```import igraph as ig
from sklearn.neighbors import kneighbors_graph
import leidenalg as la

k = 10

A = kneighbors_graph(X, k)
sources, targets = A.nonzero()
G = ig.Graph(directed=True)
G.add_vertices(A.shape[0])
edges = list(zip(sources, targets))
G.add_edges(edges)

partition = la.find_partition(G, la.RBConfigurationVertexPartition, resolution_parameter = 1, seed = 42)
```

I am using scikit-learn to get a kNN graph `A`, then I need to manually convert it into a `igraph` object `G` which is then passed into `find_partition()`. I hope I do the convertion correctly (the results make sense so hopefully it's okay)... But it would be great if `find_partition` could accept `A` directly, which is simply a `scipy` sparse binary matrix in Compressed Sparse Row format.

Or am I doing it the wrong way?

**Comment by vtraag** [comment]
I understand that might be convenient. But it would be better if that were implemented directly in `python-igraph`. Perhaps you can open an issue for it there?
