### ISSUE TITLE
Huge difference between leiden and louvain algorithm

### ISSUE THREAD

**Issue by kaizen89** [vtraag/leidenalg#28]
I have tried `seurat::FindClusters` using either louvain or leidenalg and the results are very different.
```
library(seurat)
pbmc_small <-  FindClusters(pbmc_small, resolution = 0.5, algorithm = 1) 
# 1 cluster
pbmc_small <-  FindClusters(pbmc_small, resolution = 0.5, algorithm = 4) 
# 8 clusters
```
Is this normal?

**Comment by vtraag** [comment]
With very different you mean the 1 cluster versus the 8 clusters? Yes, that is possible. Louvain may incorrectly group together weakly connected subgroups, which should actually be split. See https://arxiv.org/abs/1810.08473 for details.

**Comment by kaizen89** [comment]
Indeed that's big difference, was not expecting such difference
