### ISSUE TITLE
what is initial_membership?

### ISSUE THREAD

**Issue by richardehughes** [vtraag/leidenalg#30]
Is this a dictionary of mapping nodes to partitions?   Can't find an example of this in the documentation.

**Comment by vtraag** [comment]
No, it is a vector of nodes to their cluster membership. That is, if `initial_membership[i] == c` then node `i` (where `0 <= i < n`, with `n` the number of nodes) is in community `c`. This is also stated in the [documentation](https://leidenalg.readthedocs.io/en/latest/reference.html#leidenalg.VertexPartition.MutableVertexPartition), see the explanation of the `initial_membership` parameter.
