### ISSUE TITLE
Weighted vs. Unweighted graphs

### ISSUE THREAD

**Issue by samchiacchia** [vtraag/leidenalg#31]
When I use CPM or ModularityVertexPartition to cluster an undirected, weighted network in which all edges are non-zero, they both return 0 partitions (i.e. # clusters = # nodes). Is there a parameter that I'm not seeing that needs to be changed when working with weighted graphs?

**Comment by vtraag** [comment]
You need to pass the argument `weights`, see the [documentation](https://leidenalg.readthedocs.io/en/latest/reference.html#leidenalg.find_partition). If that doesn't solve your issue, could you perhaps provide the exact code you run? That way I can see what might be going wrong. It is difficult to say more without seeing the code.

**Comment by samchiacchia** [comment]
When I add the weights argument it doesn't change the output. Below I've provided two examples in which the first graph is a simplified version of the second. In the first graph, there are 3 nodes, 2 of which are connected. In the second graph there are 3 nodes, all 3 of which are connected, but only 2 of them are connected with strong weights (100 vs. 0.1). ModularityVertexPartition is able to identify the partition in the first example, but not in the second (as seen in the example). CPM does not identify any partition in either example (i.e. # clusters = # nodes). 

`### Example with unweighted graph
print('Example 1:')
a = pd.DataFrame(zip([0,1,0], [1,0,0], [0,0,0])).to_numpy()
# Print adj matrix
print('Adj matrix:')
print(a)
b = ig.Graph.Weighted_Adjacency(a.tolist())
p = la.find_partition(b, partition_type = la.ModularityVertexPartition, seed = 42)
print('membership', p.membership)


### Example with weighted graph
print('Example 2:')
a = pd.DataFrame(zip([1,100,0.1], [100,1,0.1], [0.1,0.1,1])).to_numpy()
b = ig.Graph.Weighted_Adjacency(a.tolist())
np.fill_diagonal(a, 0)
# Print adj matrix
print('Adj matrix')
print(a)

# Assign weight to graph 
b.es['weight'] = a.flatten()
# Print weights
print('Edge Weights:')
for e in b.es():
    print(e['weight'])

# Compute partition
p = la.find_partition(b, weights=a.flatten(), partition_type = la.ModularityVertexPartition, seed = 42)
print('membership', p.membership)

`

**Comment by vtraag** [comment]
The membership of `[0,0,0]` is optimal in this case.

```python
a = pd.DataFrame(zip([0,100,0.1], [100,0,0.1], [0.1,0.1,0])).to_numpy()
b = ig.Graph.Weighted_Adjacency(a.tolist(), mode=ig.ADJ_UNDIRECTED)
p = la.find_partition(b, weights='weight', partition_type = la.ModularityVertexPartition, seed = 42)
print('membership', p.membership)
print(b.modularity([0, 0, 0], weights='weight'))
print(b.modularity([0, 0, 1], weights='weight'))
```
yields the output
```
membership [0, 0, 0]
0.0
-1.9920239363148753e-06
```

Regarding CPM, the result will depend on the `resolution_parameter` that you specify. By default that is set to 1, which might not give the results you are interested in (it nearly never does).
