### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by adamgayoso** [vtraag/leidenalg#34]
Hello,

I came across this issue when trying to install this in a Google Colab environment. 

```
ERROR: Could not build wheels for leidenalg which use PEP 517 and cannot be installed directly
```

I assume this has to do with the new release as 0.7 has previously worked.

Thanks!

**Comment by vtraag** [comment]
You probably tried to install it when the proper wheel for Google Colab was not yet available (something went wrong with automatic uploading). Please try again now, and let me know if everything works well.

**Comment by adamgayoso** [comment]
Looks like it works now! Thanks
