### ISSUE TITLE
RBConfigurationVertexPartition  vs. RBERVertexPartition

### ISSUE THREAD

**Issue by scribu** [vtraag/leidenalg#4]
Hi,

I'm confused about the difference between these two partition methods. Both classes have the same description:

> Implements Reichardt and Bornholdt’s Potts model with a configuration null model.

* https://leidenalg.readthedocs.io/en/latest/reference.html#rbconfigurationvertexpartition
* https://leidenalg.readthedocs.io/en/latest/reference.html#rbervertexpartition

Is this a documentation error?

PS: Thanks for releasing this library! It runs much faster than the built-in igraph community detection methods.

**Comment by vtraag** [comment]
Sorry for the late reply, I missed it during the holidays. 

Indeed there is a documentation error. The RBERVertexPartition documentation should read
> Implements Reichardt and Bornholdt’s Potts model with an Erdős-Rényi null model.

The formal description that follows is correct though. See also the referenced publications for more detail.

I'll correct it in the next update. Thanks for spotting it!
