### ISSUE TITLE
max_comm_size error

### ISSUE THREAD

**Issue by PatrickPata** [vtraag/leidenalg#50]
Hi,

Thank you for continuously developing this algorithm! I previously used the louvain algorithm to analyze my thesis and now I am doing the reanalysis with the leiden algorithm and multiplex. I stumbled into this error in which the partitioning with multiplex requires a max_comm_size (first cell in photo) but when I add any max_comm_size value (second cell in photo) it does not recognize this as an argument. This is not an issue with the regular partitioning though.

I solved this for my purposes by removing the max_comm_size statements in lines 100 and 164. I'm sure there is a better way to address the bug.

Cheers,
Patrick

![max_comm_size_error](https://user-images.githubusercontent.com/9817907/97070871-925d6400-1590-11eb-841a-c3fb4df6137a.png)

**Comment by TomKellyGenetics** [comment]
I get this error as well. When calling `find_partition_multiplex` only. Not when calling `find_partition` (which passes defaults of `max_comm_size=0`) in version 0.8.2.

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NameError: name 'max_comm_size' is not defined

Detailed traceback: 
  File "/Users/tom/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/leidenalg/functions.py", line 164, in find_partition_multiplex
    optimiser.max_comm_size = max_comm_size;
```

**Comment by TomKellyGenetics** [comment]
I've managed to identify the issue. Default arguments are missing here:

[src/functions.py:100](https://github.com/vtraag/leidenalg/blob/1b4ed5ebc6eca7fb000233980f77754da054a32c/src/functions.py#L100)
```{diff}
- def find_partition_multiplex(graphs, partition_type, n_iterations=2, seed=None, **kwargs):
+ def find_partition_multiplex(graphs, partition_type, n_iterations=2, max_comm_size=0, seed=None, **kwargs):
```

**Comment by TomKellyGenetics** [comment]
Correcting this and reinstalling from source fixes the issue for me:

```
 python setup.py bdist_wheel 
python -m pip install dist/leidenalg-0.7.0.post2.dev207+g0734bff.d20201106-cp38-cp38-macosx_10_9_x86_64.whl
```

**Comment by TomKellyGenetics** [comment]
Here's a successful test job on the updated version.

```
python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56) 
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph as ig
>>> import leidenalg as la
>>> G1 = ig.Graph.Famous("Zachary")
>>> G2 = ig.Graph.Famous("Zachary")
>>> optimiser = la.Optimiser()
>>> membership, improv = la.find_partition_multiplex([G1, G2], la.ModularityVertexPartition);
>>> membership
[1, 1, 1, 1, 3, 3, 3, 1, 0, 0, 3, 1, 1, 1, 0, 0, 3, 1, 0, 1, 0, 1, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0]
```

**Comment by pamphilusTex** [comment]
I fixed this problem and found another problem.
Here are the codes:

```
import igraph
import leidenalg as la

g = igraph.Graph()
h = igraph.Graph()

g_vertex_names = ['a', 'b', 'c', 'd', 'e']
h_vertex_names = ['a', 'b', 'c', 'd', 'e', 'f']

g_edges = [('a', 'b'), ('a', 'c'), ('b', 'c'), ('a', 'd'),
           ('d', 'e')]
h_edges = [('a', 'b'), ('a', 'c'), ('b', 'c'), ('b', 'a'),
           ('c', 'b'), ('d', 'e'), ('d', 'f'), ('e', 'f'),
           ('e', 'd'), ('f', 'd'), ('f', 'e')]

g.add_vertices(g_vertex_names)
h.add_vertices(h_vertex_names)

g.add_edges(g_edges)
h.add_edges(h_edges)

net_list = [g, h]
optimiser = la.Optimiser()
membership, improv = la.find_partition_multiplex(
    net_list,
    la.ModularityVertexPartition)
```
`Traceback (most recent call last):
  File "x:/xxxxx/test/test.py", line 37, in <module>
    la.ModularityVertexPartition)
  File "x:\xxxxxx\leidenalg\functions.py", line 169, in find_partition_multiplex
    improvement = optimiser.optimise_partition_multiplex(partitions, layer_weights, n_iterations)
  File "x:\xxxxxx\leidenalg\Optimiser.py", line 402, in optimise_partition_multiplex
    is_membership_fixed)
ValueError: Unknown exception`
