### ISSUE TITLE
plan for working with NetworkX?

### ISSUE THREAD

**Issue by ma-ji** [vtraag/leidenalg#54]
Hi, thanks for this great package! Do you have a plan to develop a version for working with NetworkX? Lots of users will be benefited.

**Comment by vtraag** [comment]
No, I don't have such a plan. However, converting from (and to)`networkx` is straightforward: https://igraph.org/python/doc/igraph.Graph-class.html#from_networkx. This should add just one line to your code.

**Comment by vtraag** [comment]
If there is any problem with this functionality, feel free to re-open this issue.
