### ISSUE TITLE
Adding/Removing an edge and re-run Leiden

### ISSUE THREAD

**Issue by gebaltso** [vtraag/leidenalg#57]
Hello again! I have a question: I have a network and run Leiden on it. After some calculations I may add or remove an edge from the network (only edge not node), and after that I want to re-run Leiden to see if there is any change in the partitioning (which should only be around the affected area). Is it possible to re-run Leiden in incremental way? Because one major problem is the different partitions I get every time I run the algorithm even when I give the same seed.
Would the use of temporal help? In the manner that I use the initial graph and the changed one(that which has edge changes).

**Comment by vtraag** [comment]
I'm closing this for now. If you do still have an issue @gebaltso, feel free to re-open this issue (or open a new issue if it is a new problem of course).
