### ISSUE TITLE
name 'configuration' is not defined

### ISSUE THREAD

**Issue by JinJieGan** [vtraag/leidenalg#64]
when i used 'pip install leidenalg' and try to import it:
![image](https://user-images.githubusercontent.com/66105373/114292112-d270be80-9abe-11eb-915d-83e547941aa4.png)
anybody help me ?

**Comment by vtraag** [comment]
This is presumably a problem with how you installed `python-igraph`. Could you show us how you installed that, and which version you installed? Additionally, you seem to be using Anaconda. You can simply install both `python-igraph` and `leidenalg` from the `conda-forge` channel. Is there any particular reason why you are installing using `pip`?

**Comment by JinJieGun** [comment]
thx, I tried `pip uninstall leidenalg` and `pip uninstall pycairo ` and `pip install leidenalg` again,it works.
This is my code:
`import leidenalg
import igraph as ig
def leiden(data,vertex):
    edges = []
    for i in range(len(data)):
        edges.append((data[i,0], data[i,1]))
    G = ig.Graph()
    G.add_vertices(list(vertex))
    G.add_edges(edges)  
    part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition) `
Actually, i don't know how to install both python-igraph and leidenalg from the conda-forge channel.

**Comment by JinJieGun** [comment]
thx, I tried `pip uninstall leidenalg` and `pip uninstall pycairo ` and `pip install leidenalg` again,it works.
This is my code:
def leiden(data,vertex):
    edges = []
    for i in range(len(data)):
        edges.append((data[i,0], data[i,1]))
    G = ig.Graph()
    G.add_vertices(list(vertex))
    G.add_edges(edges)  
    part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition)  
Actually, i don't know how to install both python-igraph and leidenalg from the conda-forge channel.

**Comment by JinJieGun** [comment]
thx, I tried `pip uninstall leidenalg`  `pip uninstall cairocffi`, and`pip install leidenalg`,it works.
Actually, i don't know how to install both python-igraph and leidenalg from the conda-forge channel.

**Comment by vtraag** [comment]
If you are using Anaconda, you can install from the `conda-forge` channel simply using `conda install -c conda-forge python-igraph leidenalg`. If you prefer to use the graphical user interface (Anaconda Navigator), please see further instructions in [Anaconda's documentation](https://docs.anaconda.com/anaconda/navigator/tutorials/manage-channels/).
