### ISSUE TITLE
`ig.plot(partition)` doesn't work

### ISSUE THREAD

**Issue by RongqinChen** [vtraag/leidenalg#69]
Dear Vincent,
Thanks for the excellent work!

I'm getting a AttributeError when I try to plot the partitioning result.

Version of my igraph and leidenalg are 0.9.0 and 0.8.4 separately.
Code for testing is copied from the document, which is 

```python
import leidenalg as la
import igraph as ig

G = ig.Graph.Famous('Zachary')

partition = la.find_partition(G, la.ModularityVertexPartition)

print(partition)

ig.plot(partition) 
```

The error that arise is
```txt
    ig.plot(partition) 
  File "my_env/lib/python3.7/site-packages/igraph/drawing/__init__.py", line 488, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))
  File "my_env/lib/python3.7/site-packages/igraph/drawing/__init__.py", line 126, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)
  File "my_env/lib/python3.7/site-packages/igraph/drawing/utils.py", line 410, in __getattr__
    raise AttributeError("plotting not available")
AttributeError: plotting not available
```

Thank you for your time.

**Comment by vtraag** [comment]
Good to see you managed to solve the issue @RongqinChen! If any others pass by here, the problem is that `cairo` was not installed. You can install either `pycairo` or `cairocffi`, both should work in principle.

**Comment by RongqinChen** [comment]
Yes, I solved the problem by installing the packages you mentioned. Thank you for your reply.
