### ISSUE TITLE
[Feature request] fixed nodes

### ISSUE THREAD

**Issue by iosonofabio** [vtraag/leidenalg#7]
Hi there,

I'm applying Leiden and similar algorithms and find it extremely useful to fix the community of some nodes to the initial value, e.g. those will never change. I have a version of this based off Louvain and Smart Local Moving here:

https://github.com/iosonofabio/slmpy

and would like to ask whether this is already present in the Leiden repo or whether you have an interest in adding it - I could also add it via a PR.

From what I understand from the code, the change would be simple. Basically we put an additional property in the optimizer with a list of fixed nodes and an if/else clause inside the while loop that moves nodes around - so if the chosen node is up for moving we skip it instead.

What do you think?

**Comment by vtraag** [comment]
Hi Fabio,

Yes, this sounds good! Please open an PR indeed with the proposed change, that would be easiest. Note that we do not only have to skip the nodes when deciding to move, we also need to skip those nodes when adding nodes to the (initial) queue. It is fastest to do this with an array of booleans, indicating for each node whether it is fixed or not.

Thanks!

Vincent

**Comment by iosonofabio** [comment]
Awesome, I'll try to make a PR that has the broad strokes and you'll guide me from there :-)
thanks
Fabio

**Comment by iosonofabio** [comment]
Hi Vincent,

I'm looking at the underlying igraph C library. We could add an attribute "fixed" to each vertex of the graph directly, or hack the constructor of MutableVertexPartition to take that list/boolean array. Any preference? I'd go with the first one.

Thanks
Fabio

**Comment by vtraag** [comment]
It is not so easy to work with those attributes in my experience, so in practice it is easier to work with an array directly (similar to how the weights are handled now).

**Comment by vtraag** [comment]
Implementation in #9 is merged to `develop`.
