### ISSUE TITLE
quality() vs modularity?

### ISSUE THREAD

**Issue by silverbullet1472** [vtraag/leidenalg#72]
Hello Traag,  
Thanks your work on this library, it **really** helps our research a lot!!

However, I notice that:  
If we use modularity for partition,  
`
fp = la.find_partition(G, la.ModularityVertexPartition, n_iterations=100, weights='weight')
`

And when retrieve the 'q', 'modularity' , the value is much **smaller** than what quality() function gives:  

`mp = la.ModularityVertexPartition(G,weights='weight', initial_membership=fp.membership)  `
`mp.quality() # 0.753  `
`mp.modularity  # 0.281  `
`mp.q`

So my question is:  

- How is q or modularity calculated (are they the same thing?)
- I look up the source code and didn't find where they are defined, but I read your c++ code on quality function and notice that it's **'unscaled version of modularity'**. What does this mean?  I see in your code you finally returns **'q/m'**. (https://github.com/vtraag/leidenalg/blob/master/src/leidenalg/ModularityVertexPartition.cpp)  So I guess this comment should be deleted?

Sorry to bother you.

**Comment by vtraag** [comment]
> * How is q or modularity calculated (are they the same thing?)

`mp.quality()` is calculed using the weights from the `weight` attribute that you indicate. `mp.modularity` does not take into account the weights. It also does not correctly take the directionality of the graph into account. In short, you should use `mp.quality()`, but not `mp.modularity`, unless you have an unweighted, undirected graph, in which case the two should be identical.

> * I guess this comment should be deleted?

Yes, quite right, it can be removed from the source code. It was previously unscaled, but then people got confused, but I did not remove that comment.

**Comment by silverbullet1472** [comment]
Thanks for explanation! 
Btw, is there a way to scale the quality output for CPM?  Because I saw in gephi's leiden plugin, the quality is a number from 0 to 1.
Thanks!

**Comment by vtraag** [comment]
> Thanks for explanation!

You're welcome!

> is there a way to scale the quality output for CPM?

Yes, you can also simply scale it with (twice) the number of edges (or total edge weight), that is also what is done in the Gephi plugin.

**Comment by silverbullet1472** [comment]
I see, thanks for your work on this project, and also very professional help !

**Comment by soodimilanlouei** [comment]
Hi, 

Many thanks for your great work on this package. I have an unweighted undirected network and I used the `ModularityVertexPartition`  quality function to find communities for different values of `max_comm_size`. While it's been said above that for such a network `quality()` and `modularity` should be identical, they are not in my case. In the plot below, you can see the quality and modularity for different values of `max_comm_size` (annotated on the plot). I was wondering why they are not identical. Also, can you provide the mathematical formulation for these two quantities?
![image](https://user-images.githubusercontent.com/12864506/191773445-95db8806-d97e-42fe-91a1-062b0e309427.png)

**Comment by wongs19** [comment]
> Hi @vtraag
> 
> Many thanks for making available such great package. In one of your comments, you mentioned the following:
> 
> mp.quality() is calculed using the weights from the weight attribute that you indicate. mp.modularity does not take into account the weights. It also does not correctly take the directionality of the graph into account. In short, you should use mp.quality(), but not mp.modularity, unless you have an unweighted, undirected graph, in which case the two should be identical.
> 
> Check the C++ files to compute the different modularity approaches, I noticed that quality is computed as follows: double q = (2.0 - this->graph->is_directed())*mod
> 
> If my observation is correct. Then, modularity takes into account the weights, and thus, quality as well. The difference between quality and modularity is: 1) for undirected graphs quality = 2* mod, but 2) for directed graphs quality= mod.
> 
> Am I correct? If so, it should not make difference whether to use modularity or quality to assess the goodness of the community detection.
> 
> Kind regards, Ivan

I have the same problems. The result which ModularityVertexPartition funtion return is confused. Hope @vtraag can reply. Thanks!
