### ISSUE TITLE
"Get coarse node list" ends the the process of from_coarse_partition(partition_agg, refined_partition.membership) 

### ISSUE THREAD

**Issue by yottoo** [vtraag/leidenalg#75]
When running the high-level implementation of leiden algorithm, the error "Get coarse node list" always kill the process of from_coarse_partition(partition_agg, refined_partition.membership).

I noticed that in the master or the 0.8.5dev branches, this problem may be solved. Just wondering when the new version, say, 0.8.5 will release? I am thrilling to have a go. :)

**Comment by vtraag** [comment]
The next version was just released. This ended up being version 0.8.7, it should be available from PyPI now. Let me know if you still run into some error!
