### ISSUE TITLE
Weights for Leiden Algorithm

### ISSUE THREAD

**Issue by Alex-Mathai-98** [vtraag/leidenalg#92]
Hey @vtraag : 

Just a small question here. I see a possible argument `weights` that can be fed to the leiden  function in cdlib.

But in the documentation :  https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.leiden.html#cdlib.algorithms.leiden

I see that `Supported Graph Types` does not include `weighted graph`.

What do both of these mean ? Is this contradictory ?

**Comment by vtraag** [comment]
Thanks for reporting this @Alex-Mathai-98 ! It seems that the information is incorrect in the `cdlib` library, I would suggest opening an issue in https://github.com/GiulioRossetti/cdlib/issues. The `leidenalg` library supports both directed and weighted graphs.
