### ISSUE TITLE
How much is the space and time complexity of leiden algorithm?

### ISSUE THREAD

**Issue by TaskeHAMANO** [vtraag/leidenalg#94]
I have checked several sources but could not find any description. Let me ask a question regarding complexity. 
[It is noted](https://perso.uclouvain.be/vincent.blondel/research/louvain.html) that the time complexity of Louvain clustering is O(n logn). [As Leiden algorithm is faster than Louvain](https://www.nature.com/articles/s41598-019-41695-z/figures/8), I think it may have better time complexity.
I would like to refer this to select a computational resource.

**Comment by vtraag** [comment]
As far as I know there is no theoretical result of the time complexity of Louvain or Leiden, only empirical analyses that suggest it roughly scales as O(n) or O(n log n), with n being the number of nodes. Experimental results shows that Leiden roughly scales similar to Louvain, see [Fig. 5](https://www.nature.com/articles/s41598-019-41695-z/figures/5), but with a smaller constant.

Regarding the memory required, in addition to the memory for the graph itself, which is O(n + m), the memory required for the algorithm itself is O(n), with m being the number of edges.

**Comment by TaskeHAMANO** [comment]
@vtraag 
Thank you for providing a special insight! It helped me a lot.
